//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyNote.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigureNote
    {
        public string NodeID { get; set; }
        public string FontNote { get; set; }
        public Nullable<int> SizeNote { get; set; }
        public Nullable<int> Boldtxt { get; set; }
        public Nullable<int> Italictxt { get; set; }
        public Nullable<int> Underlinwtxt { get; set; }
        public Nullable<int> Striketxt { get; set; }
        public Nullable<int> Colortxt { get; set; }
    
        public virtual Note Note { get; set; }
    }
}
